/**
 * goosed-sdk - TypeScript SDK for goosed API
 */

export { GoosedClient } from './client.js';
export {
    GoosedException,
    GoosedAuthError,
    GoosedNotFoundError,
    GoosedAgentNotInitializedError,
    GoosedServerError,
    GoosedConnectionError,
    normalizeSessionError,
} from './client.js';
export type {
    Session,
    CleanupEmptySessionResult,
    Message,
    MessageContent,
    MessageMetadata,
    ToolInfo,
    CallToolResponse,
    SSEEvent,
    SSEEventType,
    SessionReplyRequest,
    SessionReplyResponse,
    SessionCancelRequest,
    SessionEventsOptions,
    SessionSSEEvent,
    SessionErrorContext,
    SessionErrorEnvelope,
    SessionErrorLayer,
    SessionErrorSeverity,
    SessionSuggestedAction,
    TokenState,
    SystemInfo,
    ExtensionResult,
    GoosedClientOptions,
    ImageData,
    UploadResult,
    Recipe,
    RecipeManifest,
    ScheduledJob,
    ListSchedulesResponse,
    RunNowResponse,
    ScheduleSessionInfo,
    PromptTemplate,
    PromptListResponse,
    PromptContentResponse,
    OutputFile,
} from './types.js';
